### ISSUE TITLE
RunJobFlow error

### ISSUE THREAD

**Issue by Dinju** [tc/elastic-mapreduce-ruby#3]
Hi,

I am getting a the following error while trying to run the ./elastic-mapreduce --create

My knowledge on Ruby is low and I am not able to figure out as well . Please throw some light on the same.

The following error is getting thrown.
INFO Exception Retriable invalid response returned from RunJobFlow: {"Error"=>{"Type"=>"Sender", "Code"=>"InternalFailure", "Details"=>#<TypeError: String can't be coerced into Fixnum>}} while calling RunJobFlow on Amazon::Coral::ElasticMapReduceClient, retrying in 3.0 seconds.

**Comment by tc** [comment]
hi, what parameters did you run with --create?

**Comment by Dinju** [comment]
Hi,
I just tried running them with the default parameters.Here is the credentials file I am attaching along with this mail.

This was the error that was getting thrown when I ran with the normal emr cli./home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/coral/httpdestinationhandler.rb:23: warning: else without rescue is uselessinternal:lib/rubygems/custom_require:29:in `require': /home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/coral/httpdestinationhandler.rb:19: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)/home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/coral/httpdestinationhandler.rb:36: syntax error, unexpected keyword_end, expecting $end   from <internal:lib/rubygems/custom_require>:29:in`require' from /home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/coral/awsquery.rb:6:in `<top (required)>'  from <internal:lib/rubygems/custom_require>:29:in`require' from internal:lib/rubygems/custom_require:29:in `require' from /home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/coral/service.rb:8:in`<top (required)>'   from internal:lib/rubygems/custom_require:29:in `require' from <internal:lib/rubygems/custom_require>:29:in`require' from /home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/coral/elasticmapreduceclient.rb:6:in `<top (required)>'    from <internal:lib/rubygems/custom_require>:29:in`require' from internal:lib/rubygems/custom_require:29:in `require' from /home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/client.rb:6:in`<top (required)>' from internal:lib/rubygems/custom_require:29:in `require' from <internal:lib/rubygems/custom_require>:29:in`require' from /home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/commands.rb:7:in `<top (required)>'   from <internal:lib/rubygems/custom_require>:29:in`require' from internal:lib/rubygems/custom_require:29:in `require' from /home/dinju/elastic-mapreduce-cli/elastic-mapreduce-ruby/elastic-mapreduce-cli.rb:5:in`<top (required)>'  from internal:lib/rubygems/custom_require:29:in `require' from <internal:lib/rubygems/custom_require>:29:in`require' from ./elastic-mapreduce:6:in `<main>'
