### ISSUE TITLE
EMR non compatible with ruby 1.9 or later versions

### ISSUE THREAD

**Issue by tanzeelrana** [tc/elastic-mapreduce-ruby#7]
The latest version of the emr does not work with the newer versions of ruby 
I had to change the colons with when and got it to work to an extent but when I'm trying to create a job flow it is giving me further errors that I am unable to figure out 

TRana:elastic-mapreduce-ruby trana$ ./elastic-mapreduce --create --alive --log-uri s3n://my-example-bucket/logs Created job flow j-36U2JMAE73054

Error: undefined method `to_str' for #<RuntimeError:0x007fed8c280a88>
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/retry_delegator.rb:51:in`rescue in method_missing'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/amazon/retry_delegator.rb:42:in `method_missing'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/client.rb:88:in`run_jobflow'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/commands.rb:1324:in `enact'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/commands.rb:47:in`block in enact'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/commands.rb:47:in `each'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/commands.rb:47:in`enact'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/commands.rb:2428:in `create_and_execute_commands'
/Users/trana/elastic-mapreduce-cli/elastic-mapreduce-ruby/elastic-mapreduce-cli.rb:13:in`<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in`require'
./elastic-mapreduce:6:in `<main>'

**Comment by tc** [comment]
Is this report for the official EMR release or this fork?

**Comment by tanzeelrana** [comment]
for the official EMR release.

**Comment by tc** [comment]
You might want to post this ticket to their issue tracker then, alternatively, you can try this fork which is 1.9 comp. Hasn't been 2.0 tested yet.
